// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDVin_i9JfttVJtyRcXzDB3eBLmGEFeg',
    appId: '1:768057281417:web:0f8089884af2ac33feef58',
    messagingSenderId: '768057281417',
    projectId: 'siru-original',
    authDomain: 'siru-original.firebaseapp.com',
    storageBucket: 'siru-original.firebasestorage.app',
    measurementId: 'G-94B95DNVHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwfdxGNCtoIco_vSSaBf4zG1l5IfWuk9c',
    appId: '1:768057281417:android:9aff0aaacefd6eb4feef58',
    messagingSenderId: '768057281417',
    projectId: 'siru-original',
    storageBucket: 'siru-original.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQ4F_nROO4Qo_JsIyEkOSh7S1vzhHNog',
    appId: '1:768057281417:ios:92071bbbe8b0085efeef58',
    messagingSenderId: '768057281417',
    projectId: 'siru-original',
    storageBucket: 'siru-original.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQ4F_nROO4Qo_JsIyEkOSh7S1vzhHNog',
    appId: '1:768057281417:ios:92071bbbe8b0085efeef58',
    messagingSenderId: '768057281417',
    projectId: 'siru-original',
    storageBucket: 'siru-original.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPDVin_i9JfttVJtyRcXzDB3eBLmGEFeg',
    appId: '1:768057281417:web:aaae378a9d7e5c1afeef58',
    messagingSenderId: '768057281417',
    projectId: 'siru-original',
    authDomain: 'siru-original.firebaseapp.com',
    storageBucket: 'siru-original.firebasestorage.app',
    measurementId: 'G-873FPVN72W',
  );
}
